export class FontConstants {
  // Sizes (fp)
  static readonly TITLE: number = 30;
  static readonly SUBTITLE: number = 22;
  static readonly BODY: number = 15;
  static readonly TOKEN_CODE: number = 32;
  static readonly SERVICE_NAME: number = 16;
  static readonly CAPTION: number = 13;
  static readonly TINY: number = 10;
  static readonly TAB_LABEL: number = 10;
  static readonly DIALOG_TITLE: number = 17;
  static readonly DIALOG_BUTTON: number = 15;
  static readonly SMALL_TEXT: number = 12;
  static readonly XSMALL_TEXT: number = 11;

  // Weights
  static readonly WEIGHT_BOLD: number = 700;
  static readonly WEIGHT_SEMIBOLD: number = 600;
  static readonly WEIGHT_MEDIUM: number = 500;
  static readonly WEIGHT_LIGHT: number = 300;
}